#ifndef UTILITY_CONSTANTS_GLSL
#define UTILITY_CONSTANTS_GLSL

#define PI 3.14159265359
#define TWO_PI 6.28318530718
#define INV_PI 0.31830988618

#define INFINITY 1000000000.0

#define INVALID_UINT_VALUE 0xFFFFFFFFu
#define ERROR_UINT_VALUE 0xFFFFFFFEu

#define RENDER_MODE_POSITION 0
#define RENDER_MODE_NORMAL 1
#define RENDER_MODE_GEOMETRIC_NORMAL 2
#define RENDER_MODE_UV 3
#define RENDER_MODE_BASE_COLOR 4
#define RENDER_MODE_NORMAL_MAP 5
#define RENDER_MODE_TANGENT 6
#define RENDER_MODE_BI_TANGENT 7
#define RENDER_MODE_OBJECT_DESCRIPTOR 8
#define RENDER_MODE_TRIANGLE 9
#define RENDER_MODE_MOTION 10
#define RENDER_MODE_FACE 11
#define RENDER_MODE_COLORMAP 12
#define RENDER_MODE_DISK_BASED_SAMPLING_INTERSECTIONS 13
#define RENDER_MODE_RESTIRSSS_SEARCH_RADIUS 14

#endif