macro(_add_package_Optix)
    find_package(Optix)
    if (OPTIX_FOUND)
        Message(STATUS "OptiX: Enabled")
        add_definitions(-DOPTIX_SUPPORT)
        include_directories(${OPTIX_INCLUDE_DIR})
        LIST(APPEND PACKAGE_SOURCE_FILES ${OPTIX_HEADERS})
        source_group(OPTIX FILES ${OPTIX_HEADERS})
        set(USING_OPTIX "YES")
    else ()
        Message(STATUS "OptiX: Disabled")
    endif ()
endmacro()